name: ar_rtc_engine
description: Flutter plugin for anyRTC Video SDK.
version: 4.1.0
homepage: https://www.anyrtc.io

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.12.13+hotfix.6'
dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  e2e: ^0.2.1
  flutter_driver:
    sdk: flutter
  pedantic: ^1.8.0
  build_runner: ^1.7.0
  json_serializable: ^3.2.0
flutter:
  plugin:
    platforms:
      android:
        package: org.ar.rtc_engine
        pluginClass: ArRtcEnginePlugin
      ios:
        pluginClass: ArRtcEnginePlugin

